name: build
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths: 
      - '**.cs'
      - '**.csproj'
  pull_request:
    branches:
      - '*'
    paths: 
      - '**.cs'
      - '**.csproj'
      
env:
  Configuration: 'Release'

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '7.0.x'
    - name: Restore worloads
      run: dotnet workload restore --ignore-failed-sources
    - run: dotnet build --configuration ${{ env.Configuration }}
    
