name: release
on:
  workflow_dispatch:
  release:
    types:
      - published
      
env:
  NugetDir: ${{ github.workspace }}/nuget
  DotnetVersion: '7.0.x'
  ProjectPath: 'TooLargeTool/TooLargeTool.csproj'
  NugetSource: https://api.nuget.org/v3/index.json
  GithubSource: https://nuget.pkg.github.com/Leo506/index.json
  
defaults:
  run:
    shell: pwsh
    
jobs:
  create_and_push_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: ${{ env.DotnetVersion }}

      - name: Restore workloads
        run: dotnet workload restore --ignore-failed-sources
        
      - name: Pack
        run: dotnet pack ${{ env.ProjectPath }} --configuration Release --output ${{ env.NugetDir }}

      - name: Prepare to publish
        run: dotnet nuget add source --username Leo506 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Leo506/index.json"

      - name: Push to Nuget.org
        run: dotnet nuget push ${{ env.NugetDir }}/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.GithubSource }} --skip-duplicate
